export const EnglishQuestions = [
    { "sr": 1, "question": "I don't like using difficult words, even if they help in better communication.", "score": "positive" },
    { "sr": 2, "question": "Is doing math problems easy for you?", "score": "negative" },
    { "sr": 3, "question": "Do you enjoy playing physical games ?", "score": "negative" },
    { "sr": 4, "question": "I do not use my leisure time in drawing three-dimensional Pictures?", "score": "positive" },
    { "sr": 5, "question": "Can you recognize music patterns after hearing them?", "score": "negative" },
    { "sr": 6, "question": "Are you interested in learning about plants and animal species of the world?", "score": "negative" },
    { "sr": 7, "question": "I don't like showing my good feelings on my face.", "score": "positive" },
    { "sr": 8, "question": "Do you understand yourself well?", "score": "negative" },
    { "sr": 9, "question": "Does life give you many challenges?", "score": "negative" },
    { "sr": 10, "question": "Do public speakers impress you a lot?", "score": "negative" },
    { "sr": 11, "question": "I don't spend my time doing calculations and quantification", "score": "positive" },
    { "sr": 12, "question": "Do you like yoga exercises?", "score": "negative" },
    { "sr": 13, "question": "Is it easy for you to spot patterns and shapes when you see a picture?", "score": "negative" },
    { "sr": 14, "question": "I do not enjoy playing a musical instrument.", "score": "positive" },
    { "sr": 15, "question": "Do changes in the weather, falling leaves, the sound of wind, and the warm sun fascinate you?", "score": "negative" },
    { "sr": 16, "question": "Do you find talking to people in person more effective as it grows out from personal interaction?", "score": "negative" },
    { "sr": 17, "question": "Are your life values not important to you?", "score": "positive" },
    { "sr": 18, "question": "Are you aware of your strengths and weaknesses?", "score": "negative" },
    { "sr": 19, "question": "Do you have habit of reading books ?", "score": "negative" },
    { "sr": 20, "question": "Do you prefer to solve problems logically?", "score": "negative" },
    { "sr": 21, "question": "Don't you enjoy playing cricket?", "score": "positive" },
    { "sr": 22, "question": "Are you interested in understanding the anatomical structure of human body?", "score": "negative" },
    { "sr": 23, "question": "Can you create your own musical patterns?", "score": "negative" },
    { "sr": 24, "question": "Does collecting flowers and leaves not make you happy?", "score": "positive" }, { "sr": 25, "question": "Do you love making friends?", "score": "negative" },
    { "sr": 26, "question": "Do you enjoy reading philosophical books?", "score": "negative" }, { "sr": 27, "question": "Don't you strive for self-fulfillment?", "score": "positive" },
    { "sr": 28, "question": "Don't you get excited about participating in debates?", "score": "positive" },
    { "sr": 29, "question": "Do you find it very interesting to read about mathematicians?", "score": "negative" },
    { "sr": 30, "question": "Are you attracted to doing gymnastics?", "score": "negative" },
    { "sr": 31, "question": "I don't draw the images that come to my mind.", "score": "positive" },
    { "sr": 32, "question": "Do you try not to miss music concerts when they happen in your town?", "score": "negative" },
    { "sr": 33, "question": "Are you interested in studying different animal species?", "score": "negative" },
    { "sr": 34, "question": "Don't you like working as a good team member?", "score": "positive" },
    { "sr": 35, "question": "Are you inspired by the life stories of great people?", "score": "negative" },
    { "sr": 36, "question": "Do you prefer studying subjects about humans and their behavior?", "score": "negative" },
    { "sr": 37, "question": "Is reading novels your passion?", "score": "negative" },
    { "sr": 38, "question": "Don't you want to become a computer programmer?", "score": "positive" },
    { "sr": 39, "question": "Do you like play football and volleyball?", "score": "negative" },
    { "sr": 40, "question": "Do you like using colored markers for charts or drawings?", "score": "negative" },
    { "sr": 41, "question": "Aren't you good at copying sounds and mimicking sound and language patterns of others?", "score": "positive" },
    { "sr": 42, "question": "do you like Geography as your favorite subject?", "score": "negative" },
    { "sr": 43, "question": "Are you sensitive to other people's feelings and ideas?", "score": "negative" },
    { "sr": 44, "question": "Don't you have a strong sense of identity and purpose?", "score": "positive" },
    { "sr": 45, "question": "Can you often predict future events correctly?", "score": "negative" },
    { "sr": 46, "question": "Do you like writing stories, poems, or jokes for your school magazine?", "score": "negative" },
    { "sr": 47, "question": "Do you compromise with unorganised way of doing things?", "score": "negative" },
    { "sr": 48, "question": "If you could choose a profession, wouldn't you like to be an actor or a dancer?", "score": "positive" },
    { "sr": 49, "question": "Can you easily understand 3D geometry and measurements in math?", "score": "negative" },
    { "sr": 50, "question": "Are you always looking for a chance to make music your career?", "score": "negative" },
    { "sr": 51, "question": "Aren't you curious about how mountains, rivers, and deltas form?", "score": "positive" },
    { "sr": 52, "question": "Do you try to convince others with your ideas and thoughts?", "score": "negative" },
    { "sr": 53, "question": "Is Psychology your favorite subject?", "score": "negative" },
    { "sr": 54, "question": "Don't you like people who value truth, beauty, and goodness?", "score": "positive" },
    { "sr": 55, "question": "Do you miss opportunity to learn a new language?", "score": "positive" },
    { "sr": 56, "question": "Do you prefer clear answers in discussions?", "score": "negative" },
    { "sr": 57, "question": "Would you like to become a sports coach?", "score": "negative" },
    { "sr": 58, "question": "Isn't photography your passion?", "score": "positive" },
    { "sr": 59, "question": "Do you respect poets, musicians, and famous composers?", "score": "negative" },
    { "sr": 60, "question": "Do you find studying different types of storms, waves, and seas exciting?", "score": "negative" },
    { "sr": 61, "question": "I do not take any interest in conflict resolution of people.", "score": "positive" },
    { "sr": 62, "question": "Do you feel internally motivated and determined?", "score": "negative" },
    { "sr": 63, "question": "Are you attracted to the unique aspects of different cultures?", "score": "negative" },
    { "sr": 64, "question": "Are you influenced by people who communicate and speak effective language?", "score": "negative" },
    { "sr": 65, "question": "I do not prefer such friends who think logically and rationally.", "score": "positive" }, { "sr": 66, "question": "Do you have a lot of physical energy?", "score": "negative" },
    { "sr": 67, "question": "Can you quickly identify and describe objects, shapes, and colors?", "score": "negative" },
    { "sr": 68, "question": "Doesn't music make you feel more spiritual?", "score": "positive" },
    { "sr": 69, "question": "Is it passionate for me of taking photos and videos of natural events?", "score": "negative" },
    { "sr": 70, "question": "Are you good at persuading people?", "score": "negative" },
    { "sr": 71, "question": "are you not able to assess yourself well?", "score": "positive" },
    { "sr": 72, "question": "Do meditation and relaxation help me change my attitude towards problems?", "score": "negative" },
    { "sr": 73, "question": "Do you use one new word every day in your conversations with friends?", "score": "negative" },
    { "sr": 74, "question": "Do you enjoy making mathematical models?", "score": "negative" }, { "sr": 75, "question": "Don't you prefer swimming to stay physically fit?", "score": "positive" },
    { "sr": 76, "question": "Do you learn a lot through shapes, patterns, designs, and images?", "score": "negative" },
    { "sr": 77, "question": "Can you create a parody if you like a melody?", "score": "negative" },
    { "sr": 78, "question": "I do not want to become a Botanist?", "score": "positive" },
    { "sr": 79, "question": "Is it entertaining as well as challenging for me to organize an event?", "score": "negative" },
    { "sr": 80, "question": "Do you use creative wisdom and insight to make decisions?", "score": "negative" },
    { "sr": 81, "question": "I am not very concerned about my self-image.", "score": "positive" },
    { "sr": 82, "question": "Is it hard for you to remember and recite your favorite poetry?", "score": "positive" },
    { "sr": 83, "question": "Do you try to understand the main idea of a theory or phenomenon?", "score": "negative" },
    { "sr": 84, "question": "Do you want to become a famous athlete?", "score": "negative" },
    { "sr": 85, "question": "Do images and patterns of what you want to learn automatically come to your mind?", "score": "positive" },
    { "sr": 86, "question": "Can you easily recognize different musical instruments in a song?", "score": "negative" },
    { "sr": 87, "question": "Do you love visiting botanical gardens or national parks?", "score": "negative" },
    { "sr": 88, "question": "People do not call me a philosopher ?", "score": "positive" },
    { "sr": 89, "question": "You do not stop working once you start something?", "score": "negative" },
    { "sr": 90, "question": "Do you strive for self-realization?", "score": "negative" }
];

export const categories = [
    { name: "Linguistic", questions: [10, 19, 37, 46, 64, 73, 1, 28, 55, 82] },
    { name: "Logical", questions: [2, 20, 29, 47, 56, 74, 83, 11, 38, 65] },
    { name: "Bodily Kinesthetic", questions: [3, 12, 30, 39, 57, 66, 84, 21, 48, 75] },
    { name: "Spatial", questions: [13, 22, 40, 49, 67, 76, 4, 31, 58, 85] },
    { name: "Musical", questions: [5, 23, 32, 50, 59, 77, 86, 14, 41, 68] },
    { name: "Naturalistic", questions: [6, 15, 33, 42, 60, 69, 87, 24, 51, 78] },
    { name: "Inter-personal", questions: [16, 25, 43, 52, 70, 79, 7, 34, 61, 88] },
    { name: "Intra-personal", questions: [8, 26, 35, 53, 62, 80, 89, 17, 44, 71] },
    { name: "Existential", questions: [9, 18, 36, 45, 63, 72, 90, 27, 54, 81] }
];

